services:
  mysql:
    image: mysql:8.4
    container_name: it-management-mysql
    restart: unless-stopped

    environment:
      MYSQL_ROOT_PASSWORD: rootpassword
      MYSQL_DATABASE: it_management
      MYSQL_USER: it_user
      MYSQL_PASSWORD: it_password

    ports:
      - "3306:3306"

    volumes:
      - mysql_data:/var/lib/mysql

volumes:
  mysql_data:

